name: MineGIT-bedrock

on:
  workflow_dispatch:
    inputs:
      should_add_op:
        type: boolean
        default: false
        description: Whether to apply the value of op_name input.
        required: true
      setup:
        description: 'setup and generate the files?'
      op_name:
        type: string
        required: false
        description: The Minecraft username of a player to make an operator.
      eula_agree:
        type: boolean
        required: true
        description: Do you agree to the Minecraft EULA? https://www.minecraft.net/en-us/eula
      motd:
        type: string
        description: The MOTD to set in server.properties.
        default: A MineGIT server
      windows:
        type: boolean
        required: true
        description: Do you want it to be run in Linux (ubuntu)? Note that it's currently broken due to a bug from the minecraft server files
      JAR:
        type: string
        description: Get the server file. (based on your choice)

permissions:
  contents: write

jobs:
  GitBIT:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: 
    if: inputs.windows == true
    then: ubuntu-latest
    else: windows-latest

    steps:
      - name: clone repo locally
        uses: actions/checkout@v4

      - name: import Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "microsoft"

      - name: install_dependencies
        if: inputs.windows
        run: |
          sudo apt install unzip


      - name: setup ngrok
        if: inputs.windows
        uses: dsmirc/ngrok-tunnel-action@cd
        with:
          timeout: 6h
          port: 19132 
          ngrok_authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
          tunnel_type: tcp


        - name: Ngrok
          run: | 
           Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
           Expand-Archive ngrok.zip
           .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
           Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
           Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
           .\ngrok\ngrok.exe tcp 19132
           echo "::set-output name=tunnel-url::$( curl http://127.0.0.1:4040/api/tunnels | jq -r ".tunnels[0].public_url" )"
           
      - name: Grab
        if: inputs.windows
        run: |
         wget -O "server.zip" "${{ inputs.JAR }}"
         unzip server.zip -d server


      - name: Grab
        run: |
         wget -O "server.zip" "${{ inputs.JAR }}"
         Expand-Archive -Force server.zip -DestinationPath server


      - name: Generate Server Files
        if: github.event.inputs.setup == '1'
        run: |
           chmod +x ./server/bedrock_server
           LD_LIBRARY_PATH=. ./server/bedrock_server
        continue-on-error: true

      - name: Change MOTD
        run: node ./scripts/modify-motd.js "${{ inputs.motd }}"

      - name: Run Server
        if: ${{ inputs.should_add_op && inputs.windows }}
        run: |
          if [ "${{ inputs.should_add_op }}" = true ]; then
            printf "op ${{ inputs.op_name }}" | chmod +x ./server/bedrock_server && LD_LIBRARY_PATH=. ./server/bedrock_server
          else
            chmod +x ./server/bedrock_server && LD_LIBRARY_PATH=. ./server/bedrock_server
          fi


        - name: Run Server
          if: inputs.should_add_op
          run: |
            if ($env:should_add_op -eq "true") {
            echo "op $env:op_name" | ./server/bedrock_server.exe
            } else {
            ./server/bedrock_server.exe
            }

      - name: Save to GitHub
        if: inputs.windows
        run: |
          git config --global http.postBuffer 157286400
          rm -r server/behavior_packs
          rm -r server/resource_packs
          git pull
          git config user.name github-actions
          git config user.email actions@github.com
          git add server
          git commit -m "Generate bedrock server files"
          git push
